version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: rag-postgres
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: Mena2107@!
      POSTGRES_DB: rag_chat_storage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama   # stores models persistently
    # Optional: you can pre-pull models here if supported

  app:
    build: .
    image: rag-chat-storage:latest
    environment:
      API_KEY: key1,key2,key3
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rag_chat_storage
      SPRING_DATASOURCE_USERNAME: rag_user
      SPRING_DATASOURCE_PASSWORD: Mena2107@!
      SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434
      SPRING_AI_OLLAMA_CHAT_MODEL: gemma3:4b
    ports:
      - "8083:8084" 
    depends_on:
      - postgres
      - ollama

volumes: 
  pgdata:
  ollama-data:
